// Generated by WebFx

module webfx.demos.responsivedesign.application {

    // Direct dependencies modules
    requires javafx.graphics;

    // Exported packages
    exports webfx.demos.responsivedesign;

    // Provided services
    provides javafx.application.Application with webfx.demos.responsivedesign.CustomResponsiveDesignApplication;

}