// Generated by WebFx

module webfx.framework.client.orm.reactive.visual {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires webfx.extras.cell;
    requires webfx.extras.label;
    requires webfx.extras.type;
    requires webfx.extras.visual;
    requires webfx.framework.client.i18n;
    requires webfx.framework.client.orm.reactive.dql;
    requires webfx.framework.client.orm.reactive.entities;
    requires webfx.framework.shared.orm.domainmodel;
    requires webfx.framework.shared.orm.entity;
    requires webfx.framework.shared.orm.expression;
    requires webfx.platform.shared.json;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.framework.client.orm.reactive.mapping.entities_to_visual;
    exports webfx.framework.client.orm.reactive.mapping.entities_to_visual.conventions;

}