// Generated by WebFx

module webfx.tutorials.colorfulcircles.application.javafx {

    // Direct dependencies modules
    requires webfx.kit.javafx;
    requires webfx.platform.java.appcontainer.impl;
    requires webfx.platform.java.shutdown.impl;
    requires webfx.platform.shared.log.impl.simple;
    requires webfx.tutorials.colorfulcircles.application;

}