// Generated by WebFx

module javafx.base {

    // Direct dependencies modules
    requires java.base;

    // Exported packages
    exports com.sun.javafx;
    exports com.sun.javafx.binding;
    exports com.sun.javafx.collections;
    exports com.sun.javafx.event;
    exports javafx.beans;
    exports javafx.beans.binding;
    exports javafx.beans.property;
    exports javafx.beans.value;
    exports javafx.collections;
    exports javafx.collections.transformation;
    exports javafx.event;
    exports javafx.util;

}