// Generated by WebFx

module webfx.extras.visual {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.graphics;
    requires webfx.extras.cell;
    requires webfx.extras.label;
    requires webfx.extras.type;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.extras.visual;
    exports webfx.extras.visual.impl;

}