// Generated by WebFx

module webfx.platform.shared.submitlistener {

    // Direct dependencies modules
    requires java.base;
    requires webfx.platform.shared.appcontainer;
    requires webfx.platform.shared.log;
    requires webfx.platform.shared.submit;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.platform.server.services.submitlistener;

    // Used services
    uses webfx.platform.server.services.submitlistener.SubmitListener;

    // Provided services
    provides webfx.platform.shared.services.appcontainer.spi.ApplicationModuleInitializer with webfx.platform.server.services.submitlistener.SubmitListenerModuleInitializer;

}