// Generated by WebFx

module webfx.tutorials.colorfulcircles.application {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.graphics;

    // Exported packages
    exports webfx.tutorials.colorfulcircles;

    // Provided services
    provides javafx.application.Application with webfx.tutorials.colorfulcircles.ColorfulCircles4;

}