// Generated by WebFx

module mongoose.backend.application.javafx {

    // Direct dependencies modules
    requires javafx.controls;
    requires mongoose.backend.activities.cloneevent;
    requires mongoose.backend.activities.cloneevent.routing;
    requires mongoose.backend.application;
    requires mongoose.client.navigationarrows.java;
    requires mongoose.shared.domain;
    requires webfx.framework.client.activity;
    requires webfx.framework.client.domain;
    requires webfx.framework.client.uirouter;
    requires webfx.kit.javafx;
    requires webfx.platform.client.storage.java;
    requires webfx.platform.client.websocket.java;
    requires webfx.platform.client.windowhistory.java;
    requires webfx.platform.client.windowlocation.java;
    requires webfx.platform.shared.appcontainer.java;
    requires webfx.platform.shared.json.java;
    requires webfx.platform.shared.log.simple;
    requires webfx.platform.shared.query.java;
    requires webfx.platform.shared.resource.java;
    requires webfx.platform.shared.scheduler.java;
    requires webfx.platform.shared.shutdown.java;
    requires webfx.platform.shared.update.java;
    requires webfx.platform.shared.util;

    // Exported packages
    exports mongoose.backend.activities.event.clone.javafx;

}