// Generated by WebFx

module mongoose.backend.application.javafx {

    // Direct dependencies modules
    requires javafx.controls;
    requires mongoose.backend.activities.cloneevent;
    requires mongoose.backend.activities.cloneevent.routing;
    requires mongoose.shared.domain;
    requires webfx.framework.client.activity;
    requires webfx.framework.client.uirouter;
    requires webfx.framework.shared.domain;
    requires webfx.platform.shared.util;

    // Exported packages
    exports mongoose.backend.activities.event.clone.javafx;

}