// This java module file was generated by WebFx

module webfx.fxkit.extracontrols {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires webfx.fxkit.util;
    requires webfx.platform.client.uischeduler;
    requires webfx.platform.shared.scheduler;
    requires webfx.platform.shared.util;

    requires webfx.fxkit.launcher;

    // Exported packages
    exports webfx.fxkit.extra.cell.collator;
    exports webfx.fxkit.extra.cell.renderer;
    exports webfx.fxkit.extra.cell.rowstyle;
    exports webfx.fxkit.extra.controls.displaydata;
    exports webfx.fxkit.extra.controls.displaydata.chart;
    exports webfx.fxkit.extra.controls.displaydata.datagrid;
    exports webfx.fxkit.extra.controls.html;
    exports webfx.fxkit.extra.displaydata;
    exports webfx.fxkit.extra.displaydata.impl;
    exports webfx.fxkit.extra.type;
    exports webfx.fxkit.extra.util;

}