// Generated by WebFx

module webfx.demo.spacefx.application.gluon {

    // Direct dependencies modules
    requires webfx.demo.spacefx.application;
    requires webfx.kit.javafx;
    requires webfx.platform.java.appcontainer.impl;
    requires webfx.platform.java.resource.impl;
    requires webfx.platform.java.scheduler.impl;
    requires webfx.platform.java.shutdown.impl;
    requires webfx.platform.java.storage.impl;
    requires webfx.platform.shared.log.impl.simple;

}