// Generated by WebFx

module mongoose.backend.activities.events.routing {

    // Direct dependencies modules
    requires mongoose.client.util;
    requires webfx.framework.client.uirouter;
    requires webfx.framework.shared.operation;
    requires webfx.framework.shared.router;
    requires webfx.platform.client.windowhistory;

    // Exported packages
    exports mongoose.backend.activities.events.routing;
    exports mongoose.backend.operations.events;

}