// Generated by WebFx

module webfx.demos.service.forecast {

    // Direct dependencies modules
    requires java.base;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.demos.service.services.forecast;
    exports webfx.demos.service.services.forecast.spi;

    // Resources packages
    opens webfx.demos.service.services.forecast.images;

    // Used services
    uses webfx.demos.service.services.forecast.spi.ForecastServiceProvider;

}