// Generated by WebFx

module webfx.demos.mandelbrot.math {

    // Direct dependencies modules
    requires java.base;

    // Exported packages
    exports webfx.demos.mandelbrot.math;
    exports webfx.demos.mandelbrot.math.original;

}