// Generated by WebFx

module webfx.platform.client.webassembly {

    // Direct dependencies modules
    requires java.base;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.platform.client.services.webassembly;
    exports webfx.platform.client.services.webassembly.spi;

    // Used services
    uses webfx.platform.client.services.webassembly.spi.WebAssemblyProvider;

}