// Generated by WebFx

module webfx.demos.mandelbrot.computation {

    // Direct dependencies modules
    requires java.base;

    // Exported packages
    exports webfx.demos.mandelbrot.computation;
    exports webfx.demos.mandelbrot.computation.original;

}