// Generated by WebFx

module webfx.demo.colorfulcircles.application {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.graphics;

    // Exported packages
    exports webfx.demo.colorfulcircles;

    // Provided services
    provides javafx.application.Application with webfx.demo.colorfulcircles.ColorfulCircles;

}