// Generated by WebFx

module webfx.kit.javafxgraphics.peers {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.graphics;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.kit.mapper.peers.javafxgraphics;
    exports webfx.kit.mapper.peers.javafxgraphics.markers;

}