// This java module file was generated by WebFx

module webfx.platform.client.windowlocation.java {

    // Direct dependencies modules
    requires webfx.platform.client.websocketbus;
    requires webfx.platform.client.windowhistory;
    requires webfx.platform.client.windowlocation;
    requires webfx.platform.shared.bus;

    // Exported packages
    exports webfx.platform.client.services.windowlocation.spi.impl.java;

    // Provided services
    provides webfx.platform.client.services.windowlocation.spi.WindowLocationProvider with webfx.platform.client.services.windowlocation.spi.impl.java.JavaWindowLocationProvider;

}