// Generated by WebFx

module webfx.demos.fx2048.application {

    // Direct dependencies modules
    requires java.base;
    requires java.logging;
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;

    // Exported packages
    exports io.fxgame.game2048;

    // Resources packages
    opens io.fxgame.game2048;

    // Provided services
    provides javafx.application.Application with io.fxgame.game2048.Game2048;

}