// Generated by WebFx

module webfx.demos.service.forecast.random {

    // Direct dependencies modules
    requires java.base;
    requires webfx.demos.service.forecast;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.demos.service.services.forecast.spi.impl.random;

    // Provided services
    provides webfx.demos.service.services.forecast.spi.ForecastServiceProvider with webfx.demos.service.services.forecast.spi.impl.random.RandomForecastServiceProvider;

}