// Generated by WebFx

module webfx.lib.controlsfx.validation {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;

    // Exported packages
    exports impl.org.controlsfx;
    exports impl.org.controlsfx.skin;
    exports org.controlsfx.control.decoration;
    exports org.controlsfx.tools;
    exports org.controlsfx.validation;
    exports org.controlsfx.validation.decoration;

    // Resources packages
    opens impl.org.controlsfx.control.validation;

}