// Generated by WebFx

module mongoose.backend.activities.monitor.routing {

    // Direct dependencies modules
    requires webfx.framework.client.uirouter;
    requires webfx.framework.shared.operation;
    requires webfx.framework.shared.router;
    requires webfx.platform.client.windowhistory;

    // Exported packages
    exports mongoose.backend.activities.monitor.routing;
    exports mongoose.backend.operations.monitor;

}