// Generated by WebFx

module webfx.fxkit.util {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires webfx.platform.client.uischeduler;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.fxkit.util.properties;
    exports webfx.fxkit.util.properties.conversion;

}