// Generated by WebFx

module webfx.demos.mandelbrot.application {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires webfx.demos.mandelbrot.computation;
    requires webfx.demos.mandelbrot.worker;
    requires webfx.platform.client.uischeduler;
    requires webfx.platform.shared.json;
    requires webfx.platform.shared.log;
    requires webfx.platform.shared.resource;
    requires webfx.platform.shared.worker;
    requires webfx.kit.launcher;

    // Exported packages
    exports webfx.demos.mandelbrot;
    exports webfx.demos.mandelbrot.canvastracer;

    // Resources packages
    opens webfx.demos.mandelbrot;

    // Provided services
    provides javafx.application.Application with webfx.demos.mandelbrot.MandelbrotApplication;

}