// Generated by WebFx

module webfx.demos.mandelbrot.application {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires webfx.platform.client.uischeduler;
    requires webfx.platform.shared.log;
    requires webfx.platform.shared.resource;

    // Exported packages
    exports webfx.demos.mandelbrot;
    exports webfx.demos.mandelbrot.canvastracer;
    exports webfx.demos.mandelbrot.canvastracer.model;
    exports webfx.demos.mandelbrot.mandelbrotmodel;

    // Resources packages
    opens webfx.demos.mandelbrot;

    // Provided services
    provides javafx.application.Application with webfx.demos.mandelbrot.MandelbrotApplication;

}