// Generated by WebFx

module webfx.platform.shared.update {

    // Direct dependencies modules
    requires java.base;
    requires webfx.platform.shared.buscall;
    requires webfx.platform.shared.datasource;
    requires webfx.platform.shared.json;
    requires webfx.platform.shared.serial;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.platform.shared.services.update;
    exports webfx.platform.shared.services.update.spi;
    exports webfx.platform.shared.services.update.spi.impl;

    // Used services
    uses webfx.platform.shared.services.update.spi.UpdateServiceProvider;

    // Provided services
    provides webfx.platform.shared.services.buscall.spi.BusCallEndpoint with webfx.platform.shared.services.update.ExecuteUpdateBusCallEndpoint, webfx.platform.shared.services.update.ExecuteUpdateBatchBusCallEndpoint;
    provides webfx.platform.shared.services.serial.spi.SerialCodec with webfx.platform.shared.services.update.UpdateArgument.ProvidedSerialCodec, webfx.platform.shared.services.update.UpdateResult.ProvidedSerialCodec, webfx.platform.shared.services.update.GeneratedKeyBatchIndex.ProvidedSerialCodec;

}