// Generated by WebFx

module webfx.extras.visual.controls {

    // Direct dependencies modules
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires webfx.extras.cell;
    requires webfx.extras.label;
    requires webfx.extras.visual;
    requires webfx.kit.util;
    requires webfx.platform.client.uischeduler;

    // Exported packages
    exports webfx.extras.visual.controls;

}