// Generated by WebFx

module webfx.platform.java.appcontainer.impl {

    // Direct dependencies modules
    requires webfx.platform.shared.appcontainer;

    // Exported packages
    exports webfx.platform.java.services.appcontainer.spi.impl;

    // Provided services
    provides webfx.platform.shared.services.appcontainer.spi.ApplicationContainerProvider with webfx.platform.java.services.appcontainer.spi.impl.JavaApplicationContainerProvider;

}