// Generated by WebFx

module webfx.extras.webtext.controls.registry {

    // Direct dependencies modules
    requires java.base;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.extras.webtext.controls.registry;
    exports webfx.extras.webtext.controls.registry.spi;

    // Used services
    uses webfx.extras.webtext.controls.registry.spi.WebTextRegistryProvider;

}