// Generated by WebFx

module mongoose.backend.operations.document {

    // Direct dependencies modules
    requires javafx.controls;
    requires javafx.graphics;
    requires mongoose.backend.operations.generic;
    requires mongoose.client.personaldetails;
    requires mongoose.shared.entities;
    requires webfx.framework.client.controls;
    requires webfx.framework.shared.operation;
    requires webfx.framework.shared.orm.domainmodel;
    requires webfx.kit.launcher;
    requires webfx.platform.shared.submit;
    requires webfx.platform.shared.util;

    // Exported packages
    exports mongoose.backend.operations.entities.document;
    exports mongoose.backend.operations.entities.document.cart;
    exports mongoose.backend.operations.entities.document.multiplebookings;
    exports mongoose.backend.operations.entities.document.registration;
    exports mongoose.backend.operations.entities.document.security;

}