// Generated by WebFx

module webfx.platform.shared.json.gwt {

    // Direct dependencies modules
    requires gwt.user;
    requires webfx.platform.shared.json;

    // Exported packages
    exports webfx.platform.shared.services.json.spi.impl.gwt;

}