// Generated by WebFx

module webfx.framework.shared.orm.domainmodelservice {

    // Direct dependencies modules
    requires java.base;
    requires webfx.extras.label;
    requires webfx.extras.type;
    requires webfx.framework.shared.orm.domainmodel;
    requires webfx.platform.shared.log;
    requires webfx.platform.shared.query;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.framework.shared.services.domainmodel;
    exports webfx.framework.shared.services.domainmodel.spi;

    // Used services
    uses webfx.framework.shared.services.domainmodel.spi.DomainModelProvider;

}