// Generated by WebFx

module webfx.platform.shared.appcontainer.java {

    // Direct dependencies modules
    requires webfx.platform.shared.appcontainer;

    // Exported packages
    exports webfx.platform.shared.services.appcontainer.spi.impl.java;

    // Provided services
    provides webfx.platform.shared.services.appcontainer.spi.ApplicationContainerProvider with webfx.platform.shared.services.appcontainer.spi.impl.java.JavaApplicationContainerProvider;

}