// Generated by WebFx

module webfx.demo.raytracer.application.gluon {

    // Direct dependencies modules
    requires webfx.demo.raytracer.application;
    requires webfx.kit.javafx;
    requires webfx.platform.java.appcontainer.impl;
    requires webfx.platform.java.scheduler.impl;
    requires webfx.platform.java.shutdown.impl;
    requires webfx.platform.java.webworker.impl;
    requires webfx.platform.shared.json.impl;
    requires webfx.platform.shared.log.impl.simple;

}