// Generated by WebFx

module webfx.tutorial.colorfulcircles.application {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.graphics;

    // Exported packages
    exports webfx.tutorial.colorfulcircles;

    // Provided services
    provides javafx.application.Application with webfx.tutorial.colorfulcircles.ColorfulCircles4;

}