// Generated by WebFx

module webfx.platform.shared.buscalljob {

    // Direct dependencies modules
    requires webfx.platform.shared.appcontainer;
    requires webfx.platform.shared.bus;
    requires webfx.platform.shared.buscall;
    requires webfx.platform.shared.log;

    // Exported packages
    exports dev.webfx.platform.server.jobs.buscall;

    // Provided services
    provides dev.webfx.platform.shared.services.appcontainer.spi.ApplicationJob with dev.webfx.platform.server.jobs.buscall.BusCallServerJob;

}