// Generated by WebFx

module webfx.demos.service.application.javafx {

    // Direct dependencies modules
    requires webfx.demos.service.alert.javafx;
    requires webfx.demos.service.application;
    requires webfx.demos.service.forecast.random;
    requires webfx.kit.javafx;
    requires webfx.platform.java.appcontainer.impl;
    requires webfx.platform.java.scheduler.impl;
    requires webfx.platform.java.shutdown.impl;
    requires webfx.platform.shared.log.impl.simple;

}