// Generated by WebFx

module webfx.platform.java.submit.impl.jdbc {

    // Direct dependencies modules
    requires webfx.platform.java.queryupdate;
    requires webfx.platform.shared.datasource;
    requires webfx.platform.shared.submit;

    // Exported packages
    exports webfx.platform.java.services.submit.spi.impl.jdbc;

    // Provided services
    provides webfx.platform.shared.services.submit.spi.SubmitServiceProvider with webfx.platform.java.services.submit.spi.impl.jdbc.JdbcSubmitServiceProvider;

}