// Generated by WebFx

module mongoose.backend.operations.generic {

    // Direct dependencies modules
    requires java.base;
    requires javafx.graphics;
    requires webfx.extras.type;
    requires webfx.extras.visual.controls.grid;
    requires webfx.framework.client.controls;
    requires webfx.framework.client.orm.reactive.entities;
    requires webfx.framework.shared.operation;
    requires webfx.framework.shared.orm.domainmodel;
    requires webfx.framework.shared.orm.entity;
    requires webfx.framework.shared.orm.expression;
    requires webfx.platform.shared.submit;
    requires webfx.platform.shared.util;

    // Exported packages
    exports mongoose.backend.operations.entities.generic;

}