// Generated by WebFx

module webfx.demos.service.theme.dark {

    // Direct dependencies modules
    requires webfx.demos.service.theme;

    // Exported packages
    exports webfx.demos.service.services.theme.spi.impl.dark;

}