// Generated by WebFx

module webfx.platform.shared.updatelistener {

    // Direct dependencies modules
    requires java.base;
    requires webfx.platform.shared.appcontainer;
    requires webfx.platform.shared.log;
    requires webfx.platform.shared.update;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.platform.server.services.updatelistener;

    // Used services
    uses webfx.platform.server.services.updatelistener.UpdateListener;

    // Provided services
    provides webfx.platform.shared.services.appcontainer.spi.ApplicationModuleInitializer with webfx.platform.server.services.updatelistener.UpdateListenerModuleInitializer;

}