// Generated by WebFx

module webfx.lib.odometer {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.graphics;

    // Exported packages
    exports eu.hansolo.fx.odometer;
    exports eu.hansolo.fx.odometer.event;

}