// Generated by WebFx

module webfx.framework.server.querypush {

    // Direct dependencies modules
    requires java.base;
    requires webfx.framework.server.push;
    requires webfx.framework.shared.querypush;
    requires webfx.platform.shared.bus;
    requires webfx.platform.shared.log;
    requires webfx.platform.shared.query;
    requires webfx.platform.shared.scheduler;
    requires webfx.platform.shared.update;
    requires webfx.platform.shared.updatelistener;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.framework.server.services.querypush;
    exports webfx.framework.server.services.querypush.spi.impl;

    // Provided services
    provides webfx.platform.server.services.updatelistener.UpdateListener with webfx.framework.server.services.querypush.QueryPushServerService.ProvidedUpdateListener;

}