// Generated by WebFx

module webfx.demos.clock.application {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.demos.clock;
    exports webfx.demos.clock.hansolo;
    exports webfx.demos.clock.hansolo.emul;
    exports webfx.demos.clock.hansolo.events;
    exports webfx.demos.clock.hansolo.skins;
    exports webfx.demos.clock.hansolo.tools;

    // Provided services
    provides javafx.application.Application with webfx.demos.clock.ClockApplication;

}