// This java module file was generated by WebFx

module mongoose.backend.activities.organizations {

    // Direct dependencies modules
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires mongoose.backend.activities.events.routing;
    requires mongoose.backend.activities.organizations.routing;
    requires mongoose.client.activity;
    requires mongoose.shared.entities;
    requires webfx.framework.client.i18n;
    requires webfx.framework.client.uifilter;
    requires webfx.framework.client.uirouter;
    requires webfx.framework.shared.domain;
    requires webfx.framework.shared.router;
    requires webfx.platform.shared.util;

    // Implicit
    requires webfx.framework.client.activity;

    // Exported packages
    exports mongoose.backend.activities.organizations;

    // Provided services
    provides webfx.framework.client.operations.route.RouteRequestEmitter with mongoose.backend.activities.organizations.RouteToOrganizationsRequestEmitter;
    provides webfx.framework.client.ui.uirouter.UiRoute with mongoose.backend.activities.organizations.OrganizationsUiRoute;

}