// Generated by WebFx

module webfx.platform.client.windowhistory.gwt {

    // Direct dependencies modules
    requires gwt.user;
    requires java.base;
    requires jsinterop.annotations;
    requires webfx.platform.client.windowhistory.web;
    requires webfx.platform.shared.json;
    requires webfx.platform.shared.json.gwt;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.platform.client.services.windowhistory.spi.impl.gwt;
    exports webfx.platform.client.services.windowhistory.spi.impl.gwt.jsinterop;

}