// This java module file was generated by WebFx

module webfx.framework.shared.push {

    // Direct dependencies modules

    // Exported packages
    exports webfx.framework.shared.services.push;

}