// Generated by WebFx

module webfx.kit.util {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires webfx.platform.shared.util;

    // Exported packages
    exports dev.webfx.kit.util.properties;
    exports dev.webfx.kit.util.properties.conversion;

}