// Generated by WebFx

module webfx.platform.java.shutdown.impl {

    // Direct dependencies modules
    requires webfx.platform.shared.shutdown;

    // Exported packages
    exports webfx.platform.java.services.shutdown.spi.impl;

    // Provided services
    provides webfx.platform.shared.services.shutdown.spi.ShutdownProvider with webfx.platform.java.services.shutdown.spi.impl.JavaShutdownProvider;

}