// Generated by WebFx

module mongoose.frontend.application.javafx {

    // Direct dependencies modules
    requires mongoose.client.navigationarrows.java;
    requires mongoose.frontend.application;
    requires webfx.kit.javafx;
    requires webfx.platform.client.storage.java;
    requires webfx.platform.client.websocket.java;
    requires webfx.platform.client.windowhistory.java;
    requires webfx.platform.client.windowlocation.java;
    requires webfx.platform.shared.appcontainer.java;
    requires webfx.platform.shared.json.java;
    requires webfx.platform.shared.log.simple;
    requires webfx.platform.shared.query.java;
    requires webfx.platform.shared.resource.java;
    requires webfx.platform.shared.scheduler.java;
    requires webfx.platform.shared.shutdown.java;
    requires webfx.platform.shared.update.java;

}