// Generated by WebFx

module webfx.tutorials.responsivedesign.application {

    // Direct dependencies modules
    requires javafx.graphics;

    // Exported packages
    exports webfx.tutorials.responsivedesign;

    // Provided services
    provides javafx.application.Application with webfx.tutorials.responsivedesign.CustomResponsiveDesignApplication;

}