// Generated by WebFx

module webfx.tutorial.service.alert.javafx {

    // Direct dependencies modules
    requires javafx.controls;
    requires webfx.tutorial.service.alert;

    // Exported packages
    exports webfx.tutorial.service.services.alert.spi.impl.javafx;

    // Provided services
    provides webfx.tutorial.service.services.alert.spi.AlertServiceProvider with webfx.tutorial.service.services.alert.spi.impl.javafx.JavaFxAlertServiceProvider;

}