// This java module file was generated by WebFx

module mongoose.client.util {

    // Direct dependencies modules
    requires mongoose.shared.entities;
    requires webfx.framework.client.i18n;
    requires webfx.framework.shared.entity;
    requires webfx.framework.shared.expression;
    requires webfx.fxkit.extracontrols;
    requires webfx.platform.shared.log;
    requires webfx.platform.shared.util;

    // Exported packages
    exports mongoose.client.util.functions;
    exports mongoose.client.util.log;
    exports mongoose.client.util.routing;

}