// Generated by WebFx

module webfx.platform.java.storage.impl {

    // Direct dependencies modules
    requires java.base;
    requires webfx.platform.client.storage;

    // Exported packages
    exports webfx.platform.java.services.storage.spi.impl;

    // Provided services
    provides webfx.platform.client.services.storage.spi.LocalStorageProvider with webfx.platform.java.services.storage.spi.impl.JavaLocalStorageProvider;
    provides webfx.platform.client.services.storage.spi.SessionStorageProvider with webfx.platform.java.services.storage.spi.impl.JavaSessionStorageProvider;

}