// Generated by WebFx

module mongoose.frontend.application {

    // Direct dependencies modules
    requires javafx.graphics;
    requires mongoose.client.application;

    // Exported packages
    exports mongoose.frontend.application;

    // Provided services
    provides javafx.application.Application with mongoose.frontend.application.MongooseFrontendApplication;

}