// Generated by WebFx

module webfx.tutorial.service.application.javafx {

    // Direct dependencies modules
    requires webfx.kit.javafx;
    requires webfx.platform.shared.appcontainer.java;
    requires webfx.platform.shared.log.simple;
    requires webfx.platform.shared.scheduler.java;
    requires webfx.platform.shared.shutdown.java;
    requires webfx.tutorial.service.alert.javafx;
    requires webfx.tutorial.service.application;
    requires webfx.tutorial.service.forecast.random;

}