// This java module file was generated by WebFx

module mongoose.client.activities.unauthorized {

    // Direct dependencies modules
    requires javafx.graphics;
    requires webfx.framework.client.uirouter;
    requires webfx.framework.shared.domain;

    // Implicit
    requires webfx.framework.client.activity;
    requires webfx.platform.shared.util;

    // Exported packages
    exports mongoose.client.activities.unauthorized;

    // Provided services
    provides webfx.framework.client.ui.uirouter.UiRoute with mongoose.client.activities.unauthorized.UnauthorizedUiRoute;

}