// Generated by WebFx

module webfx.framework.client.controls {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires webfx.framework.client.action;
    requires webfx.framework.client.i18n;
    requires webfx.framework.client.layouts;
    requires webfx.framework.client.materialdesign;
    requires webfx.framework.client.uifilter;
    requires webfx.framework.client.util;
    requires webfx.framework.shared.domain;
    requires webfx.framework.shared.entity;
    requires webfx.framework.shared.expression;
    requires webfx.fxkit.extracontrols;
    requires webfx.fxkit.util;
    requires webfx.lib.controlsfx.validation;
    requires webfx.platform.client.uischeduler;
    requires webfx.platform.shared.json;
    requires webfx.platform.shared.scheduler;
    requires webfx.platform.shared.update;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.framework.client.ui.controls;
    exports webfx.framework.client.ui.controls.alert;
    exports webfx.framework.client.ui.controls.button;
    exports webfx.framework.client.ui.controls.dialog;
    exports webfx.framework.client.ui.controls.sheet;

    // Resources packages
    opens images.s16.controls;

}