// Generated by WebFx

module webfx.framework.client.materialdesign {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires webfx.framework.client.layouts;
    requires webfx.framework.client.util;
    requires webfx.fxkit.util;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.framework.client.ui.materialdesign.textfield;
    exports webfx.framework.client.ui.materialdesign.util;

}