// Generated by WebFx

module webfx.framework.shared.orm.dql.submit.interceptor {

    // Direct dependencies modules
    requires java.base;
    requires webfx.framework.shared.orm.datasourcemodelservice;
    requires webfx.framework.shared.orm.domainmodel;
    requires webfx.framework.shared.orm.expression;
    requires webfx.platform.shared.appcontainer;
    requires webfx.platform.shared.datascope;
    requires webfx.platform.shared.datasource;
    requires webfx.platform.shared.submit;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.framework.shared.interceptors.dqlsubmit;

    // Provided services
    provides webfx.platform.shared.services.appcontainer.spi.ApplicationModuleInitializer with webfx.framework.shared.interceptors.dqlsubmit.DqlSubmitInterceptorModuleInitializer;

}