// Generated by WebFx

module webfx.tutorial.service.alert.gwt {

    // Direct dependencies modules
    requires elemental2.dom;
    requires webfx.tutorial.service.alert;

    // Exported packages
    exports webfx.tutorial.service.services.alert.spi.impl.gwt;

}