// Generated by WebFx

module mongoose.client.calendar {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires mongoose.shared.time;
    requires webfx.framework.client.i18n;
    requires webfx.framework.client.util;
    requires webfx.kit.util;
    requires webfx.platform.shared.util;

    // Exported packages
    exports mongoose.client.businessdata.calendar;
    exports mongoose.client.businessdata.calendar.impl;
    exports mongoose.client.controls.calendargraphic;
    exports mongoose.client.controls.calendargraphic.impl;

}