// Generated by WebFx

module webfx.platform.teavm.json.impl {

    // Direct dependencies modules
    requires teavm.jso;
    requires teavm.jso.apis;
    requires webfx.platform.shared.json;

    // Exported packages
    exports webfx.platform.teavm.services.json.spi.impl;

    // Provided services
    provides webfx.platform.shared.services.json.spi.JsonProvider with webfx.platform.teavm.services.json.spi.impl.TeaVmJsonObject;

}