// Generated by WebFx

module webfx.demo.raytracer.worker {

    // Direct dependencies modules
    requires webfx.demo.raytracer.math;
    requires webfx.platform.client.webassembly;
    requires webfx.platform.shared.json;
    requires webfx.platform.shared.util;
    requires webfx.platform.shared.worker;

    // Exported packages
    exports webfx.demo.raytracer.worker;

}