// Generated by WebFx

module webfx.framework.client.operationaction {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires webfx.framework.client.action;
    requires webfx.framework.shared.authz;
    requires webfx.framework.shared.operation;
    requires webfx.kit.util;
    requires webfx.platform.client.uischeduler;
    requires webfx.platform.shared.log;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.framework.client.ui.action.operation;

}