// Generated by WebFx

module webfx.fxkit.mapper.javafxgraphics {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.graphics;
    requires webfx.fxkit.mapper;
    requires webfx.fxkit.util;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.fxkit.mapper.spi.impl.peer.javafxgraphics;

}