// Generated by WebFx

module webfx.extras.visual.controls.grid.registry {

    // Direct dependencies modules
    requires java.base;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.extras.visual.controls.grid.registry;
    exports webfx.extras.visual.controls.grid.registry.spi;

    // Used services
    uses webfx.extras.visual.controls.grid.registry.spi.VisualGridRegistryProvider;

}