// This java module file was generated by WebFx

module mongoose.backend.activities.cloneevent {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires mongoose.backend.activities.bookings.routing;
    requires mongoose.backend.activities.cloneevent.routing;
    requires mongoose.client.activity;
    requires mongoose.shared.domain;
    requires mongoose.shared.entities;
    requires webfx.framework.client.controls;
    requires webfx.framework.client.uirouter;
    requires webfx.framework.shared.domain;
    requires webfx.fxkit.util;
    requires webfx.platform.client.uischeduler;
    requires webfx.platform.shared.update;

    // Implicit
    requires webfx.platform.shared.util;
    requires webfx.framework.client.activity;
    requires webfx.framework.shared.entity;

    // Exported packages
    exports mongoose.backend.activities.cloneevent;

    // Provided services
    provides webfx.framework.client.ui.uirouter.UiRoute with mongoose.backend.activities.cloneevent.CloneEventUiRoute;

}