// Generated by WebFx

module webfx.demos.particles.application {

    // Direct dependencies modules
    requires java.base;
    requires javafx.graphics;

    // Exported packages
    exports webfx.demos.particles;

    // Provided services
    provides javafx.application.Application with webfx.demos.particles.ParticlesApplication;

}