// This java module file was generated by WebFx

module webfx.framework.client.uifilter {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires webfx.framework.client.activity;
    requires webfx.framework.client.i18n;
    requires webfx.framework.client.push;
    requires webfx.framework.client.util;
    requires webfx.framework.shared.domain;
    requires webfx.framework.shared.entity;
    requires webfx.framework.shared.expression;
    requires webfx.framework.shared.querypush;
    requires webfx.fxkit.extracontrols;
    requires webfx.fxkit.util;
    requires webfx.lib.rxjava;
    requires webfx.platform.client.uischeduler;
    requires webfx.platform.shared.json;
    requires webfx.platform.shared.log;
    requires webfx.platform.shared.query;
    requires webfx.platform.shared.scheduler;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.framework.client.ui.filter;
    exports webfx.framework.client.ui.filter.rx;
    exports webfx.framework.shared.orm.mapping.entity_display;

}