// Generated by WebFx

module mongoose.backend.activities.letter {

    // Direct dependencies modules
    requires javafx.base;
    requires javafx.graphics;
    requires mongoose.backend.activities.letter.routing;
    requires mongoose.backend.multilangeditor;
    requires webfx.framework.client.activity;
    requires webfx.framework.client.controls;
    requires webfx.framework.client.domain;
    requires webfx.framework.client.uirouter;
    requires webfx.fxkit.util;
    requires webfx.platform.shared.util;

    // Exported packages
    exports mongoose.backend.activities.letter;

    // Provided services
    provides webfx.framework.client.ui.uirouter.UiRoute with mongoose.backend.activities.letter.LetterUiRoute;

}