// Generated by WebFx

module webfx.extras.webtext.controls {

    // Direct dependencies modules
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires webfx.extras.webtext.controls.registry;
    requires webfx.kit.javafxgraphics.peers;

    // Exported packages
    exports webfx.extras.webtext.controls;

}