// Generated by WebFx

module mongoose.client.bookingoptionspanel {

    // Direct dependencies modules
    requires java.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires mongoose.client.aggregates;
    requires mongoose.client.businesslogic;
    requires mongoose.client.sectionpanel;
    requires mongoose.client.util;
    requires mongoose.shared.entities;
    requires mongoose.shared.time;
    requires webfx.extras.type;
    requires webfx.extras.visual;
    requires webfx.extras.visual.controls.grid;
    requires webfx.framework.client.i18n;
    requires webfx.framework.client.orm.reactive.visual;
    requires webfx.framework.shared.orm.domainmodel;
    requires webfx.framework.shared.orm.entity;
    requires webfx.framework.shared.orm.expression;
    requires webfx.kit.util;
    requires webfx.platform.shared.util;

    // Exported packages
    exports mongoose.client.controls.bookingoptionspanel;

}