// Generated by WebFx

module webfx.framework.shared.authn {

    // Direct dependencies modules
    requires java.base;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.framework.shared.services.authn;
    exports webfx.framework.shared.services.authn.spi;

    // Used services
    uses webfx.framework.shared.services.authn.spi.AuthenticationServiceProvider;

}