// Generated by WebFx

module webfx.platform.java.update.impl.jdbc {

    // Direct dependencies modules
    requires webfx.platform.java.queryupdate;
    requires webfx.platform.shared.datasource;
    requires webfx.platform.shared.update;

    // Exported packages
    exports webfx.platform.java.services.update.spi.impl.jdbc;

    // Provided services
    provides webfx.platform.shared.services.update.spi.UpdateServiceProvider with webfx.platform.java.services.update.spi.impl.jdbc.JdbcUpdateServiceProvider;

}