// Generated by WebFx

module mongoose.backend.operations.moneytransfer {

    // Direct dependencies modules
    requires javafx.graphics;
    requires mongoose.shared.entities;
    requires webfx.framework.client.controls;
    requires webfx.framework.client.orm.entity.controls;
    requires webfx.framework.shared.operation;
    requires webfx.framework.shared.orm.entity;
    requires webfx.platform.shared.submit;
    requires webfx.platform.shared.util;

    // Exported packages
    exports mongoose.backend.operations.entities.moneytransfer;

}