// Generated by WebFx

module webfx.platform.client.websocketbus.web {

    // Direct dependencies modules
    requires webfx.platform.client.websocketbus;
    requires webfx.platform.client.windowlocation;
    requires webfx.platform.shared.bus;
    requires webfx.platform.shared.json;
    requires webfx.platform.shared.resource;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.platform.client.services.websocketbus.web;

}