// Generated by WebFx

module webfx.platform.client.windowlocation.gwt {

    // Direct dependencies modules
    requires gwt.user;
    requires jsinterop.annotations;
    requires webfx.platform.client.windowlocation;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.platform.client.services.windowlocation.spi.impl.gwt;
    exports webfx.platform.client.services.windowlocation.spi.impl.gwt.jsinterop;

}