// This java module file was generated by WebFx

module webfx.platform.providers.vertx.instance {

    // Direct dependencies modules
    requires vertx.core;

    // Exported packages
    exports webfx.platform.providers.vertx.instance;

}