// Generated by WebFx

module webfx.tutorials.service.application {

    // Direct dependencies modules
    requires java.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires webfx.extras.flexbox;
    requires webfx.kit.launcher;
    requires webfx.platform.shared.util;
    requires webfx.tutorials.service.alert;
    requires webfx.tutorials.service.console;
    requires webfx.tutorials.service.forecast;

    // Exported packages
    exports webfx.tutorials.service;

    // Provided services
    provides javafx.application.Application with webfx.tutorials.service.ForecastServiceApplication;

}