// Generated by WebFx

module mongoose.client.bookingoptionspanel {

    // Direct dependencies modules
    requires java.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires mongoose.client.aggregates;
    requires mongoose.client.businesslogic;
    requires mongoose.client.sectionpanel;
    requires mongoose.client.util;
    requires mongoose.shared.entities;
    requires mongoose.shared.time;
    requires webfx.framework.client.i18n;
    requires webfx.framework.client.uifilter;
    requires webfx.framework.shared.entity;
    requires webfx.framework.shared.expression;
    requires webfx.framework.shared.util;
    requires webfx.fxkit.extracontrols;
    requires webfx.fxkit.extratype;
    requires webfx.fxkit.util;
    requires webfx.platform.shared.util;

    // Exported packages
    exports mongoose.client.controls.bookingoptionspanel;

}