// Generated by WebFx

module webfx.demos.raytracer.application {

    // Direct dependencies modules
    requires javafx.graphics;
    requires webfx.demos.mandelbrot.tracerframework;
    requires webfx.demos.raytracer.math;
    requires webfx.demos.raytracer.worker;
    requires webfx.platform.shared.json;

    // Exported packages
    exports webfx.demos.raytracer;

    // Provided services
    provides javafx.application.Application with webfx.demos.raytracer.RayTracerApplication;

}