// Generated by WebFx

module webfx.tutorials.service.theme.dark {

    // Direct dependencies modules
    requires webfx.tutorials.service.theme;

    // Exported packages
    exports webfx.tutorials.service.services.theme.spi.impl.dark;

}