// Generated by WebFx

module webfx.platform.vertx.bus.impl {

    // Direct dependencies modules
    requires vertx.core;
    requires webfx.platform.shared.bus;
    requires webfx.platform.shared.json;
    requires webfx.platform.shared.util;
    requires webfx.platform.vertx.instance;

    // Exported packages
    exports webfx.platform.vertx.services.bus.spi.impl;

    // Provided services
    provides webfx.platform.shared.services.bus.spi.BusServiceProvider with webfx.platform.vertx.services.bus.spi.impl.VertxBusServiceProvider;

}