// Generated by WebFx

module webfx.extras.webtext.controls.peers.base {

    // Direct dependencies modules
    requires javafx.base;
    requires javafx.controls;
    requires webfx.extras.webtext.controls;
    requires webfx.fxkit.javafxgraphics.mapper;
    requires webfx.fxkit.javafxgraphics.mapper.base;

    // Exported packages
    exports webfx.extras.webtext.controls.peers.base;

}