// Generated by WebFx

module mongoose.frontend.application.javafx {

    // Direct dependencies modules
    requires mongoose.client.navigationarrows.java;
    requires mongoose.frontend.application;
    requires webfx.kit.javafx;
    requires webfx.platform.java.appcontainer.impl;
    requires webfx.platform.java.resource.impl;
    requires webfx.platform.java.scheduler.impl;
    requires webfx.platform.java.shutdown.impl;
    requires webfx.platform.java.storage.impl;
    requires webfx.platform.java.websocket.impl;
    requires webfx.platform.java.windowhistory.impl;
    requires webfx.platform.java.windowlocation.impl;
    requires webfx.platform.shared.json.impl;
    requires webfx.platform.shared.log.impl.simple;
    requires webfx.platform.shared.query.impl.remote;
    requires webfx.platform.shared.update.impl.remote;

}