// This java module file was generated by WebFx

module mongoose.frontend.activities.contactus.routing {

    // Direct dependencies modules
    requires mongoose.client.util;
    requires webfx.framework.client.uirouter;
    requires webfx.platform.client.windowhistory;

    // Exported packages
    exports mongoose.frontend.activities.contactus.routing;
    exports mongoose.frontend.operations.contactus;

}