// This java module file was generated by WebFx

module webfx.lib.rxjava {

    // Direct dependencies modules
    requires java.base;

    // Exported packages
    exports rx;
    exports rx.annotations;
    exports rx.exceptions;
    exports rx.functions;
    exports rx.internal.operators;
    exports rx.internal.producers;
    exports rx.internal.util;
    exports rx.internal.util.atomic;
    exports rx.internal.util.unsafe;
    exports rx.observers;
    exports rx.plugins;
    exports rx.subjects;
    exports rx.subscriptions;

}