// Generated by WebFx

module webfx.extras.cell {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires webfx.extras.imagestore;
    requires webfx.extras.label;
    requires webfx.extras.type;
    requires webfx.extras.webtext.controls;
    requires webfx.kit.util;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.extras.cell.collator;
    exports webfx.extras.cell.renderer;
    exports webfx.extras.cell.rowstyle;

}