// Generated by WebFx

module webfx.tutorials.service.alert.javafx {

    // Direct dependencies modules
    requires javafx.controls;
    requires webfx.tutorials.service.alert;

    // Exported packages
    exports webfx.tutorials.service.services.alert.spi.impl.javafx;

    // Provided services
    provides webfx.tutorials.service.services.alert.spi.AlertServiceProvider with webfx.tutorials.service.services.alert.spi.impl.javafx.JavaFxAlertServiceProvider;

}