// Generated by WebFx

module webfx.platform.shared.log.gwt {

    // Direct dependencies modules
    requires webfx.platform.shared.log;

    // Exported packages
    exports webfx.platform.shared.services.log.spi.impl.gwt;

}