// This java module file was generated by WebFx

module webfx.platform.shared.resource.java {

    // Direct dependencies modules
    requires java.base;
    requires webfx.platform.shared.resource;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.platform.shared.services.resource.spi.impl.java;

    // Provided services
    provides webfx.platform.shared.services.resource.spi.ResourceServiceProvider with webfx.platform.shared.services.resource.spi.impl.java.JavaResourceServiceProvider;

}