// Generated by WebFx

module webfx.platform.shared.schemascope {

    // Direct dependencies modules
    requires java.base;

    // Exported packages
    exports webfx.platform.shared.schemascope;

}