// Generated by WebFx

module webfx.framework.client.push {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires webfx.framework.shared.push;
    requires webfx.platform.shared.bus;
    requires webfx.platform.shared.buscall;
    requires webfx.platform.shared.log;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.framework.client.services.push;
    exports webfx.framework.client.services.push.spi;

    // Used services
    uses webfx.framework.client.services.push.spi.PushClientServiceProvider;

}