// This java module file was generated by WebFx

module mongoose.backend.activities.loadtester.jp.routing {

    // Direct dependencies modules
    requires webfx.framework.client.uirouter;
    requires webfx.framework.shared.operation;
    requires webfx.framework.shared.router;
    requires webfx.platform.client.windowhistory;

    // Exported packages
    exports mongoose.backend.activities.loadtester.routing;
    exports mongoose.backend.activities.saveloadtest.routing;
    exports mongoose.backend.operations.loadtester;

}