// Generated by WebFx

module webfx.platform.shared.buscall {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires webfx.platform.shared.appcontainer;
    requires webfx.platform.shared.bus;
    requires webfx.platform.shared.json;
    requires webfx.platform.shared.log;
    requires webfx.platform.shared.serial;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.platform.shared.services.buscall;
    exports webfx.platform.shared.services.buscall.spi;

    // Used services
    uses webfx.platform.shared.services.buscall.spi.BusCallEndpoint;

    // Provided services
    provides webfx.platform.shared.services.appcontainer.spi.ApplicationModuleInitializer with webfx.platform.shared.services.buscall.BusCallModuleInitializer;
    provides webfx.platform.shared.services.serial.spi.SerialCodec with webfx.platform.shared.services.buscall.BusCallArgument.ProvidedSerialCodec, webfx.platform.shared.services.buscall.BusCallResult.ProvidedSerialCodec, webfx.platform.shared.services.buscall.SerializableAsyncResult.ProvidedSerialCodec;

}