// Generated by WebFx

module webfx.demo.raytracer.application {

    // Direct dependencies modules
    requires javafx.graphics;
    requires webfx.demo.mandelbrot.tracerframework;
    requires webfx.demo.raytracer.math;
    requires webfx.demo.raytracer.webworker;
    requires webfx.platform.shared.json;

    // Exported packages
    exports webfx.demo.raytracer;

    // Provided services
    provides javafx.application.Application with webfx.demo.raytracer.RayTracerApplication;

}