// Generated by WebFx

module webfx.extras.flexbox {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.graphics;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.extras.flexbox;

}