// This java module file was generated by WebFx

module webfx.platform.shared.scheduler.java {

    // Direct dependencies modules
    requires java.base;
    requires webfx.platform.shared.log;
    requires webfx.platform.shared.scheduler;

    // Exported packages
    exports webfx.platform.shared.services.scheduler.spi.impl.java;

    // Provided services
    provides webfx.platform.shared.services.scheduler.spi.SchedulerProvider with webfx.platform.shared.services.scheduler.spi.impl.java.JavaSchedulerProvider;

}