// Generated by WebFx

module webfx.platform.shared.resource {

    // Direct dependencies modules
    requires java.base;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.platform.shared.services.resource;
    exports webfx.platform.shared.services.resource.spi;

    // Used services
    uses webfx.platform.shared.services.resource.spi.ResourceServiceProvider;

}