// Generated by WebFx

module webfx.kit.javafx {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires webfx.kit.javafxgraphics.peers;
    requires webfx.kit.javafxgraphics.peers.base;
    requires webfx.kit.launcher;
    requires webfx.platform.client.uischeduler;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.kit.launcher.spi.javafx;
    exports webfx.kit.mapper.peers.javafxcontrols.javafx.skin;
    exports webfx.kit.mapper.peers.javafxgraphics.javafx;
    exports webfx.platform.client.services.uischeduler.spi.impl.javafx;

    // Provided services
    provides webfx.kit.launcher.spi.WebFxKitLauncherProvider with webfx.kit.launcher.spi.javafx.JavaFxWebFxKitLauncherProvider;
    provides webfx.platform.client.services.uischeduler.spi.UiSchedulerProvider with webfx.platform.client.services.uischeduler.spi.impl.javafx.FxUiSchedulerProvider;

}