// Generated by WebFx

module webfx.demos.service.alert.gwt {

    // Direct dependencies modules
    requires elemental2.dom;
    requires webfx.demos.service.alert;

    // Exported packages
    exports webfx.demos.service.services.alert.spi.impl.gwt;

}