// Generated by WebFx

module webfx.demos.service.application {

    // Direct dependencies modules
    requires java.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires webfx.demos.service.alert;
    requires webfx.demos.service.console;
    requires webfx.demos.service.forecast;
    requires webfx.extras.flexbox;
    requires webfx.kit.launcher;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.demos.service;

    // Provided services
    provides javafx.application.Application with webfx.demos.service.ForecastServiceApplication;

}