// Generated by WebFx

module mongoose.shared.domain {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires webfx.framework.shared.domain;
    requires webfx.framework.shared.entity;
    requires webfx.framework.shared.expression;
    requires webfx.framework.shared.util;
    requires webfx.fxkit.extratype;
    requires webfx.platform.shared.json;
    requires webfx.platform.shared.query;
    requires webfx.platform.shared.resource;
    requires webfx.platform.shared.serial;
    requires webfx.platform.shared.util;

    // Exported packages
    exports mongoose.shared.domainmodel.formatters;
    exports mongoose.shared.domainmodel.functions;
    exports mongoose.shared.domainmodel.loader;

    // Resources packages
    opens mongoose.shared.domainmodel;

}