// Generated by WebFx

module webfx.platform.vertx.instance {

    // Direct dependencies modules
    requires vertx.core;

    // Exported packages
    exports webfx.platform.vertx.services_shared_code.instance;

}