// Generated by WebFx

module webfx.platform.providers.vertx.queryupdate {

    // Direct dependencies modules
    requires java.base;
    requires java.sql;
    requires vertx.core;
    requires vertx.jdbc.client;
    requires vertx.mysql.postgresql.client.jasync;
    requires vertx.sql.common;
    requires webfx.platform.providers.vertx.instance;
    requires webfx.platform.server.updatelistener;
    requires webfx.platform.shared.datasource;
    requires webfx.platform.shared.log;
    requires webfx.platform.shared.query;
    requires webfx.platform.shared.update;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.platform.providers.vertx.queryupdate;

}