// Generated by WebFx

module webfx.tutorial.service.console {

    // Direct dependencies modules
    requires elemental2.dom;

    // Exported packages
    exports webfx.demos.service.services.console;

}