// Generated by WebFx

module webfx.demos.mandelbrot.worker {

    // Direct dependencies modules
    requires java.base;
    requires webfx.demos.mandelbrot.computation;
    requires webfx.platform.client.webassembly;
    requires webfx.platform.shared.json;
    requires webfx.platform.shared.util;
    requires webfx.platform.shared.worker;

    // Exported packages
    exports webfx.demos.mandelbrot.worker;

}