// Generated by WebFx

module webfx.kit.javafxcontrols.peers.base {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires webfx.kit.javafxgraphics.peers;
    requires webfx.kit.javafxgraphics.peers.base;

    // Exported packages
    exports webfx.kit.mapper.peers.javafxcontrols.base;

}