// Generated by WebFx

module webfx.demos.tallycounter.application {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.graphics;
    requires webfx.kit.util;

    // Exported packages
    exports eu.hansolo.fx.odometer;
    exports eu.hansolo.fx.odometer.event;
    exports webfx.demos.tallycounter;

    // Provided services
    provides javafx.application.Application with webfx.demos.tallycounter.TallyCounterApplication;

}