// Generated by WebFx

module webfx.platform.gwt.emul.javabase {

    // Direct dependencies modules
    requires gwt.user;
    requires java.base;

    // Exported packages
    exports emul.java.io;
    exports emul.java.lang;
    exports emul.java.lang.ref;
    exports emul.java.nio;
    exports emul.java.security;
    exports emul.java.text;
    exports emul.java.util;
    exports emul.java.util.concurrent;
    exports emul.java.util.concurrent.atomic;
    exports emul.java.util.function;
    exports emul.java.util.regex;

}