// Generated by WebFx

module webfx.framework.shared.operation {

    // Direct dependencies modules
    requires java.base;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.framework.shared.operation;

}