// Generated by WebFx

module webfx.platform.client.storage.java {

    // Direct dependencies modules
    requires java.base;
    requires webfx.platform.client.storage;

    // Exported packages
    exports webfx.platform.client.services.storage.spi.impl.java;

    // Provided services
    provides webfx.platform.client.services.storage.spi.LocalStorageProvider with webfx.platform.client.services.storage.spi.impl.java.JavaLocalStorageProvider;
    provides webfx.platform.client.services.storage.spi.SessionStorageProvider with webfx.platform.client.services.storage.spi.impl.java.JavaSessionStorageProvider;

}