// Generated by WebFx

module mongoose.frontend.activities.payment.routing {

    // Direct dependencies modules
    requires mongoose.client.util;
    requires mongoose.frontend.activities.cart.routing;
    requires webfx.framework.client.uirouter;
    requires webfx.platform.client.windowhistory;

    // Exported packages
    exports mongoose.frontend.activities.payment.routing;
    exports mongoose.frontend.operations.payment;

}