// Generated by WebFx

module webfx.framework.client.activity {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.framework.client.activity;
    exports webfx.framework.client.activity.impl;
    exports webfx.framework.client.activity.impl.composition;
    exports webfx.framework.client.activity.impl.composition.impl;
    exports webfx.framework.client.activity.impl.elementals.activeproperty;
    exports webfx.framework.client.activity.impl.elementals.activeproperty.impl;

}