// Generated by WebFx

module webfx.framework.shared.orm.expression {

    // Direct dependencies modules
    requires java.base;
    requires webfx.extras.type;
    requires webfx.libs.javacupruntime;
    requires webfx.platform.shared.json;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.framework.shared.orm.expression;
    exports webfx.framework.shared.orm.expression.builder;
    exports webfx.framework.shared.orm.expression.builder.terms;
    exports webfx.framework.shared.orm.expression.lci;
    exports webfx.framework.shared.orm.expression.parser;
    exports webfx.framework.shared.orm.expression.parser.javacup;
    exports webfx.framework.shared.orm.expression.parser.jflex;
    exports webfx.framework.shared.orm.expression.parser.lci;
    exports webfx.framework.shared.orm.expression.parser.lci.mock;
    exports webfx.framework.shared.orm.expression.terms;
    exports webfx.framework.shared.orm.expression.terms.function;
    exports webfx.framework.shared.orm.expression.terms.function.java;

}