// Generated by WebFx

module webfx.tutorial.colorfulcircles.application.javafx {

    // Direct dependencies modules
    requires webfx.fxkit.javafx;
    requires webfx.tutorial.colorfulcircles.application;

}