// Generated by WebFx

module webfx.platform.vertx.appcontainer.impl {

    // Direct dependencies modules
    requires java.base;
    requires vertx.bridge.common;
    requires vertx.core;
    requires vertx.web;
    requires webfx.platform.shared.appcontainer;
    requires webfx.platform.shared.shutdown;
    requires webfx.platform.shared.util;
    requires webfx.platform.vertx.instance;

    // Workaround for Vert.x 3.9.0 (see https://github.com/vert-x3/vertx-web/issues/1616)
    requires com.fasterxml.jackson.databind; // Temporary manually added (not generated by WebFx)

    // Exported packages
    exports webfx.platform.vertx.services.appcontainer.spi.impl;

    // Provided services
    provides webfx.platform.shared.services.appcontainer.spi.ApplicationContainerProvider with webfx.platform.vertx.services.appcontainer.spi.impl.VertxApplicationContainerVerticle;

}