// Generated by WebFx

module mongoose.client.presentationmodel {

    // Direct dependencies modules
    requires javafx.base;
    requires webfx.framework.shared.entity;
    requires webfx.fxkit.extracontrols;

    // Exported packages
    exports mongoose.client.presentationmodel;

}