// Generated by WebFx

module mongoose.client.presentationmodel {

    // Direct dependencies modules
    requires javafx.base;
    requires mongoose.shared.entities;
    requires webfx.extras.visual;
    requires webfx.framework.shared.entity;
    requires webfx.framework.shared.expression;

    // Exported packages
    exports mongoose.client.presentationmodel;

}