// Generated by WebFx

module mongoose.shared.domainmodel {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires webfx.extras.type;
    requires webfx.framework.client.orm.reactive.entities;
    requires webfx.framework.shared.orm.domainmodel;
    requires webfx.framework.shared.orm.dql;
    requires webfx.framework.shared.orm.entity;
    requires webfx.framework.shared.orm.expression;
    requires webfx.platform.shared.datasource;
    requires webfx.platform.shared.json;
    requires webfx.platform.shared.query;
    requires webfx.platform.shared.resource;
    requires webfx.platform.shared.serial;
    requires webfx.platform.shared.util;

    // Exported packages
    exports mongoose.shared.domainmodel;
    exports mongoose.shared.domainmodel.formatters;
    exports mongoose.shared.domainmodel.functions;
    exports mongoose.shared.services.domainmodel;

    // Resources packages
    opens mongoose.shared.domainmodel;

    // Provided services
    provides webfx.framework.shared.services.domainmodel.spi.DomainModelServiceProvider with mongoose.shared.services.domainmodel.MongooseDomainModelProvider;

}