// This java module file was generated by WebFx

module mongoose.client.personaldetails {

    // Direct dependencies modules
    requires java.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires mongoose.client.activity;
    requires mongoose.client.authn;
    requires mongoose.client.sectionpanel;
    requires mongoose.client.validation;
    requires mongoose.shared.domain;
    requires mongoose.shared.entities;
    requires webfx.framework.client.controls;
    requires webfx.framework.client.i18n;
    requires webfx.framework.client.layouts;
    requires webfx.framework.client.materialdesign;
    requires webfx.framework.client.uirouter;
    requires webfx.framework.shared.domain;
    requires webfx.framework.shared.entity;
    requires webfx.fxkit.extracontrols;
    requires webfx.fxkit.util;
    requires webfx.platform.client.uischeduler;
    requires webfx.platform.shared.util;

    // Exported packages
    exports mongoose.client.controls.personaldetails;

}