// Generated by WebFx

module webfx.platform.shared.util {

    // Direct dependencies modules
    requires java.base;
    requires java.logging;

    // Exported packages
    exports dev.webfx.platform.shared.util;
    exports dev.webfx.platform.shared.util.async;
    exports dev.webfx.platform.shared.util.collection;
    exports dev.webfx.platform.shared.util.function;
    exports dev.webfx.platform.shared.util.noreflect;
    exports dev.webfx.platform.shared.util.serviceloader;
    exports dev.webfx.platform.shared.util.tuples;
    exports dev.webfx.platform.shared.util.uuid;

}