// Generated by WebFx

module mongoose.shared.time {

    // Direct dependencies modules
    requires java.base;
    requires webfx.platform.shared.json;
    requires webfx.platform.shared.util;

    // Exported packages
    exports mongoose.shared.businessdata.time;

}