// This java module file was generated by WebFx

module mongoose.backend.activities.letter.routing {

    // Direct dependencies modules
    requires mongoose.client.util;
    requires webfx.framework.client.uirouter;
    requires webfx.platform.client.windowhistory;

    // Exported packages
    exports mongoose.backend.activities.letter.routing;
    exports mongoose.backend.operations.letter;

}