// This java module file was generated by WebFx

module mongoose.backend.activities.organizations.routing {

    // Direct dependencies modules
    requires webfx.framework.client.uirouter;
    requires webfx.framework.shared.operation;
    requires webfx.platform.client.windowhistory;

    // Exported packages
    exports mongoose.backend.activities.organizations.routing;
    exports mongoose.backend.operations.organizations;

}