// This java module file was generated by WebFx

module mongoose.frontend.activities.startbooking.routing {

    // Direct dependencies modules
    requires mongoose.client.util;
    requires webfx.framework.client.uirouter;
    requires webfx.platform.client.windowhistory;

    // Exported packages
    exports mongoose.frontend.activities.startbooking.routing;
    exports mongoose.frontend.operations.startbooking;

}