// Generated by WebFx

module webfx.demos.helloworld.application {

    // Direct dependencies modules
    requires javafx.controls;
    requires javafx.graphics;

    // Exported packages
    exports webfx.demos.helloworld;

    // Provided services
    provides javafx.application.Application with webfx.demos.helloworld.HelloWorldApplication;

}