// Generated by WebFx

module webfx.tutorial.helloworld.application.javafx {

    // Direct dependencies modules
    requires webfx.fxkit.javafx;
    requires webfx.tutorial.helloworld.application;

}