// This java module file was generated by WebFx

module webfx.tool.buildtool {

    // Direct dependencies modules
    requires java.base;
    requires java.xml;

    // Exported packages
    exports webfx.tool.buildtool;
    exports webfx.tool.buildtool.modulefiles;
    exports webfx.tool.buildtool.util.javacode;
    exports webfx.tool.buildtool.util.reusablestream;
    exports webfx.tool.buildtool.util.reusablestream.impl;
    exports webfx.tool.buildtool.util.splitfiles;

}