// Generated by WebFx

module webfx.tool.gwtsupersourcegenerator {

    // Direct dependencies modules
    requires java.base;

    // Exported packages
    exports webfx.tool.gwtsupersourcegenerator;

}