// This java module file was generated by WebFx

module webfx.tool.gwtsupersourcegenerator {

    // Direct dependencies modules
    requires java.base;
    requires java.logging;
    //requires webfx.platform.shared.log;  // Was actually in a String
    //requires webfx.platform.shared.util; // Was actually in a String

    // Exported packages
    exports webfx.tool.gwtsupersourcegenerator;

}