// Generated by WebFx

module webfx.framework.shared.orm.dql {

    // Direct dependencies modules
    requires java.base;
    requires webfx.extras.type;
    requires webfx.framework.shared.orm.expression;
    requires webfx.platform.shared.json;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.framework.shared.orm.dql;
    exports webfx.framework.shared.orm.dql.sqlcompiler;
    exports webfx.framework.shared.orm.dql.sqlcompiler.lci;
    exports webfx.framework.shared.orm.dql.sqlcompiler.lci.mock;
    exports webfx.framework.shared.orm.dql.sqlcompiler.mapping;
    exports webfx.framework.shared.orm.dql.sqlcompiler.sql;
    exports webfx.framework.shared.orm.dql.sqlcompiler.sql.dbms;
    exports webfx.framework.shared.orm.dql.sqlcompiler.terms;

}