// This java module file was generated by WebFx

module mongoose.backend.activities.letters.routing {

    // Direct dependencies modules
    requires mongoose.client.util;
    requires webfx.framework.client.uirouter;
    requires webfx.framework.shared.operation;
    requires webfx.platform.client.windowhistory;

    // Exported packages
    exports mongoose.backend.activities.letters.routing;
    exports mongoose.backend.operations.letters;

}