// Generated by WebFx

module webfx.framework.shared.orm.domainmodel {

    // Direct dependencies modules
    requires java.base;
    requires webfx.extras.label;
    requires webfx.extras.type;
    requires webfx.framework.shared.orm.dql;
    requires webfx.framework.shared.orm.expression;
    requires webfx.platform.shared.log;
    requires webfx.platform.shared.query;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.framework.shared.orm.domainmodel;
    exports webfx.framework.shared.orm.domainmodel.builder;
    exports webfx.framework.shared.orm.domainmodel.formatter;
    exports webfx.framework.shared.orm.domainmodel.lciimpl;
    exports webfx.framework.shared.services.domainmodelloader;
    exports webfx.framework.shared.services.domainmodelloader.spi;

    // Used services
    uses webfx.framework.shared.services.domainmodelloader.spi.DomainModelLoaderProvider;

}