// Generated by WebFx

module webfx.platform.java.query.impl.jdbc {

    // Direct dependencies modules
    requires webfx.platform.java.queryupdate;
    requires webfx.platform.shared.datasource;
    requires webfx.platform.shared.query;

    // Exported packages
    exports webfx.platform.java.services.query.spi.impl.jdbc;

    // Provided services
    provides webfx.platform.shared.services.query.spi.QueryServiceProvider with webfx.platform.java.services.query.spi.impl.jdbc.JdbcQueryServiceProvider;

}