// Generated by WebFx

module webfx.platform.teavm.worker.impl {

    // Direct dependencies modules
    requires java.base;
    requires teavm.interop;
    requires teavm.jso;
    requires teavm.jso.apis;
    requires webfx.platform.shared.worker;

    // Exported packages
    exports webfx.platform.teavm.services.worker.spi.impl;

}