// Generated by WebFx

module webfx.framework.client.orm.dql {

    // Direct dependencies modules
    requires java.base;
    requires webfx.platform.shared.json;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.framework.client.orm.dql;

}