// Generated by WebFx

module webfx.platform.providers.java.queryupdate {

    // Direct dependencies modules
    requires java.base;
    requires java.sql;
    requires static HikariCP;
    requires webfx.platform.shared.datasource;
    requires webfx.platform.shared.query;
    requires webfx.platform.shared.update;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.platform.providers.java.queryupdate;

}