// Generated by WebFx

module mongoose.frontend.activities.program.routing {

    // Direct dependencies modules
    requires mongoose.client.util;
    requires webfx.framework.client.uirouter;
    requires webfx.platform.client.windowhistory;

    // Exported packages
    exports mongoose.frontend.activities.program.routing;
    exports mongoose.frontend.operations.program;

}