// This java module file was generated by WebFx

module webfx.platform.shared.log {

    // Direct dependencies modules
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.platform.shared.services.log;
    exports webfx.platform.shared.services.log.spi;

    // Used services
    uses webfx.platform.shared.services.log.spi.LoggerProvider;

}