// Generated by WebFx

module mongoose.backend.activities.bookings.routing {

    // Direct dependencies modules
    requires java.base;
    requires mongoose.client.aggregates;
    requires mongoose.client.util;
    requires mongoose.frontend.activities.fees.routing;
    requires webfx.framework.client.uirouter;
    requires webfx.framework.shared.operation;
    requires webfx.framework.shared.router;
    requires webfx.platform.client.windowhistory;
    requires webfx.platform.shared.util;

    // Exported packages
    exports mongoose.backend.activities.bookings.routing;
    exports mongoose.backend.operations.bookings;

}