// Generated by WebFx

module webfx.demos.service.alert.javafx {

    // Direct dependencies modules
    requires javafx.controls;
    requires webfx.demos.service.alert;

    // Exported packages
    exports webfx.demos.service.services.alert.spi.impl.javafx;

    // Provided services
    provides webfx.demos.service.services.alert.spi.AlertServiceProvider with webfx.demos.service.services.alert.spi.impl.javafx.JavaFxAlertServiceProvider;

}