// Generated by WebFx

module webfx.framework.client.i18n.json {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires webfx.framework.client.i18n;
    requires webfx.platform.shared.json;
    requires webfx.platform.shared.resource;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.framework.client.services.i18n.spi.impl.json;

}