// This java module file was generated by WebFx

module mongoose.frontend.activities.startbooking {

    // Direct dependencies modules
    requires javafx.controls;
    requires javafx.graphics;
    requires mongoose.client.bookingprocess;
    requires mongoose.client.icons;
    requires mongoose.frontend.activities.fees.routing;
    requires mongoose.frontend.activities.options.routing;
    requires mongoose.frontend.activities.program.routing;
    requires mongoose.frontend.activities.startbooking.routing;
    requires mongoose.frontend.activities.terms.routing;
    requires mongoose.shared.entities;
    requires webfx.framework.client.action;
    requires webfx.framework.client.layouts;
    requires webfx.framework.client.uirouter;
    requires webfx.framework.client.util;
    requires webfx.framework.shared.domain;
    requires webfx.fxkit.extracontrols;
    requires webfx.fxkit.util;
    requires webfx.platform.client.uischeduler;

    // Implicit
    requires webfx.platform.shared.util;
    requires webfx.framework.client.activity;

    // Exported packages
    exports mongoose.frontend.activities.startbooking;

    // Provided services
    provides webfx.framework.client.ui.uirouter.UiRoute with mongoose.frontend.activities.startbooking.StartBookingUiRoute;

}