// Generated by WebFx

module webfx.framework.client.action {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires webfx.framework.client.i18n;
    requires webfx.framework.client.util;
    requires webfx.kit.util;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.framework.client.ui.action;
    exports webfx.framework.client.ui.action.impl;

}