// Generated by WebFx

module webfx.fxkit.javafxgraphics.mapper.base {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.graphics;
    requires webfx.fxkit.javafxgraphics.mapper;
    requires webfx.fxkit.util;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.fxkit.javafxgraphics.mapper.spi.impl.peer.base;

}