// This java module file was generated by WebFx

module mongoose.backend.activities.monitor {

    // Direct dependencies modules
    requires javafx.base;
    requires javafx.graphics;
    requires mongoose.backend.activities.monitor.routing;
    requires mongoose.client.activity;
    requires webfx.framework.client.layouts;
    requires webfx.framework.client.uifilter;
    requires webfx.framework.client.uirouter;
    requires webfx.framework.shared.domain;
    requires webfx.framework.shared.router;
    requires webfx.fxkit.extracontrols;

    // Implicit
    requires webfx.platform.shared.util;
    requires webfx.framework.client.activity;

    // Exported packages
    exports mongoose.backend.activities.monitor;

    // Provided services
    provides webfx.framework.client.operations.route.RouteRequestEmitter with mongoose.backend.activities.monitor.RouteToMonitorRequestEmitter;
    provides webfx.framework.client.ui.uirouter.UiRoute with mongoose.backend.activities.monitor.MonitorUiRoute;

}