// Generated by WebFx

module mongoose.frontend.activities.fees.routing {

    // Direct dependencies modules
    requires mongoose.client.util;
    requires webfx.framework.client.uirouter;
    requires webfx.platform.client.windowhistory;

    // Exported packages
    exports mongoose.frontend.activities.fees.routing;
    exports mongoose.frontend.operations.fees;

}