// Generated by WebFx

module webfx.extras.visual.controls.grid.peers.javafx {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires webfx.extras.cell;
    requires webfx.extras.imagestore;
    requires webfx.extras.label;
    requires webfx.extras.visual;
    requires webfx.extras.visual.controls.grid;
    requires webfx.extras.visual.controls.grid.peers.base;
    requires webfx.extras.visual.controls.grid.registry;
    requires webfx.kit.javafx;
    requires webfx.kit.javafxgraphics.peers;
    requires webfx.kit.util;
    requires webfx.platform.client.uischeduler;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.extras.visual.controls.grid.peers.javafx;
    exports webfx.extras.visual.controls.grid.registry.spi.javafx;

    // Provided services
    provides webfx.extras.visual.controls.grid.registry.spi.VisualGridRegistryProvider with webfx.extras.visual.controls.grid.registry.spi.javafx.JavaFxVisualGridRegistryProvider;

}