// Generated by WebFx

module webfx.platform.shared.shutdown {

    // Direct dependencies modules
    requires java.base;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.platform.shared.services.shutdown;
    exports webfx.platform.shared.services.shutdown.spi;
    exports webfx.platform.shared.services.shutdown.spi.impl;

    // Used services
    uses webfx.platform.shared.services.shutdown.spi.ShutdownProvider;

}