// Generated by WebFx

module webfx.demos.tallycounter.application.javafx {

    // Direct dependencies modules
    requires webfx.demos.tallycounter.application;
    requires webfx.kit.javafx;
    requires webfx.platform.java.appcontainer.impl;
    requires webfx.platform.java.shutdown.impl;
    requires webfx.platform.shared.log.impl.simple;

}