// Generated by WebFx

module mongoose.backend.application {

    // Direct dependencies modules
    requires javafx.graphics;
    requires mongoose.client.application;

    // Exported packages
    exports mongoose.backend.application;

    // Provided services
    provides javafx.application.Application with mongoose.backend.application.MongooseBackendApplication;

}