// Generated by WebFx

module webfx.framework.shared.router {

    // Direct dependencies modules
    requires java.base;
    requires webfx.framework.shared.authz;
    requires webfx.platform.shared.json;
    requires webfx.platform.shared.log;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.framework.shared.router;
    exports webfx.framework.shared.router.auth;
    exports webfx.framework.shared.router.auth.authz;
    exports webfx.framework.shared.router.auth.impl;
    exports webfx.framework.shared.router.impl;
    exports webfx.framework.shared.router.session;
    exports webfx.framework.shared.router.session.impl;
    exports webfx.framework.shared.router.util;

}