// Generated by WebFx

module mongoose.backend.activities.options {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires mongoose.backend.multilangeditor;
    requires mongoose.client.aggregates;
    requires mongoose.client.bookingcalendar;
    requires mongoose.client.businesslogic;
    requires mongoose.client.calendar;
    requires mongoose.client.icons;
    requires mongoose.frontend.activities.options;
    requires mongoose.shared.entities;
    requires mongoose.shared.time;
    requires webfx.extras.visual.controls.grid;
    requires webfx.framework.client.activity;
    requires webfx.framework.client.controls;
    requires webfx.framework.client.domain;
    requires webfx.framework.client.layouts;
    requires webfx.framework.client.orm.filter;
    requires webfx.framework.client.orm.filter.visual;
    requires webfx.framework.client.uirouter;
    requires webfx.framework.shared.orm.entity;
    requires webfx.kit.util;
    requires webfx.platform.shared.update;
    requires webfx.platform.shared.util;

    // Exported packages
    exports mongoose.backend.activities.options;

    // Provided services
    provides webfx.framework.client.ui.uirouter.UiRoute with mongoose.backend.activities.options.EditableOptionsUiRoute;

}