// This java module file was generated by WebFx

module webfx.tool.emultranslator {

    // Direct dependencies modules
    requires java.base;
    requires webfx.platform.shared.json;

    // Exported packages
    exports webfx.tool.emultranslator;

}