// Generated by WebFx

module mongoose.backend.operations.generic {

    // Direct dependencies modules
    requires java.base;
    requires javafx.graphics;
    requires webfx.framework.client.controls;
    requires webfx.framework.client.uifilter;
    requires webfx.framework.shared.domain;
    requires webfx.framework.shared.entity;
    requires webfx.framework.shared.expression;
    requires webfx.framework.shared.operation;
    requires webfx.framework.shared.util;
    requires webfx.fxkit.extracontrols;
    requires webfx.fxkit.extratype;
    requires webfx.platform.shared.update;
    requires webfx.platform.shared.util;

    // Exported packages
    exports mongoose.backend.operations.entities.generic;

}