// This java module file was generated by WebFx

module mongoose.frontend.activities.options.routing {

    // Direct dependencies modules
    requires mongoose.client.businesslogic;
    requires mongoose.client.util;
    requires webfx.framework.client.uirouter;
    requires webfx.framework.shared.entity;
    requires webfx.platform.client.windowhistory;

    // Implicit
    requires mongoose.shared.entities;
    requires mongoose.client.aggregates;

    // Exported packages
    exports mongoose.frontend.activities.options.routing;
    exports mongoose.frontend.operations.options;

}