// Generated by WebFx

module webfx.extras.imagestore {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.graphics;
    requires webfx.kit.launcher;

    // Exported packages
    exports webfx.extras.imagestore;

}