// Generated by WebFx

module webfx.extras.materialdesign {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires webfx.kit.util;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.extras.materialdesign.textfield;
    exports webfx.extras.materialdesign.util;
    exports webfx.extras.materialdesign.util.background;
    exports webfx.extras.materialdesign.util.layout;
    exports webfx.extras.materialdesign.util.scene;

}