// Generated by WebFx

module webfx.framework.client.util {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.graphics;
    requires webfx.fxkit.extracontrols;
    requires webfx.platform.shared.json;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.framework.client.ui.util.anim;
    exports webfx.framework.client.ui.util.background;
    exports webfx.framework.client.ui.util.border;
    exports webfx.framework.client.ui.util.image;
    exports webfx.framework.client.ui.util.paint;

}