// Generated by WebFx

module webfx.tutorial.responsivedesign.application {

    // Direct dependencies modules
    requires javafx.graphics;

    // Exported packages
    exports webfx.tutorial.responsivedesign;

    // Provided services
    provides javafx.application.Application with webfx.tutorial.responsivedesign.CustomResponsiveDesignApplication;

}