// Generated by WebFx

module webfx.framework.shared.util {

    // Direct dependencies modules
    requires java.base;
    requires webfx.fxkit.extratype;

    // Exported packages
    exports webfx.framework.shared.util.formatter;

}