// This java module file was generated by WebFx

module webfx.platform.shared.datasource {

    // Direct dependencies modules
    requires java.base;
    requires webfx.platform.shared.json;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.platform.shared.datasource;

}