// Generated by WebFx

module webfx.demo.mandelbrot.application {

    // Direct dependencies modules
    requires java.base;
    requires javafx.graphics;
    requires webfx.demo.mandelbrot.math;
    requires webfx.demo.mandelbrot.tracerframework;
    requires webfx.demo.mandelbrot.webworker;
    requires webfx.platform.shared.json;
    requires webfx.platform.shared.webworker;

    // Exported packages
    exports webfx.demo.mandelbrot;

    // Provided services
    provides javafx.application.Application with webfx.demo.mandelbrot.MandelbrotApplication;

}