// Generated by WebFx

module mongoose.backend.bookingdetailspanel {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires mongoose.backend.masterslave;
    requires mongoose.backend.operations.document;
    requires mongoose.backend.operations.documentline;
    requires mongoose.backend.operations.generic;
    requires mongoose.backend.operations.mail;
    requires mongoose.backend.operations.moneytransfer;
    requires mongoose.client.presentationmodel;
    requires mongoose.shared.entities;
    requires webfx.framework.client.action;
    requires webfx.framework.client.activity;
    requires webfx.framework.client.controls;
    requires webfx.framework.client.i18n;
    requires webfx.framework.client.uifilter;
    requires webfx.framework.shared.domain;
    requires webfx.framework.shared.entity;
    requires webfx.fxkit.extracontrols;
    requires webfx.fxkit.extratype;
    requires webfx.fxkit.util;
    requires webfx.platform.shared.util;

    // Exported packages
    exports mongoose.backend.controls.bookingdetailspanel;

}