// Generated by WebFx

module webfx.fxkit.extracontrols.registry {

    // Direct dependencies modules
    requires java.base;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.fxkit.extra.controls.registry;
    exports webfx.fxkit.extra.controls.registry.spi;

    // Used services
    uses webfx.fxkit.extra.controls.registry.spi.ExtraControlsRegistryProvider;

}