// This java module file was generated by WebFx

module webfx.fxkit.mapper.extracontrols {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.graphics;
    requires webfx.fxkit.extracontrols;
    requires webfx.platform.shared.util;
    requires javafx.controls;
    requires webfx.fxkit.mapper;
    requires webfx.fxkit.mapper.javafxgraphics;
    requires webfx.fxkit.mapper.javafxcontrols;

    // Exported packages
    exports webfx.fxkit.extra.cell.collator.grid;
    exports webfx.fxkit.extra.mapper.spi.peer.impl.extra;

}