// Generated by WebFx

module webfx.platform.client.windowhistory {

    // Direct dependencies modules
    requires java.base;
    requires webfx.platform.client.windowlocation;
    requires webfx.platform.shared.json;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.platform.client.services.windowhistory;
    exports webfx.platform.client.services.windowhistory.spi;
    exports webfx.platform.client.services.windowhistory.spi.impl;

    // Used services
    uses webfx.platform.client.services.windowhistory.spi.WindowHistoryProvider;

}