// This java module file was generated by WebFx

module mongoose.frontend.activities.terms {

    // Direct dependencies modules
    requires javafx.base;
    requires javafx.graphics;
    requires mongoose.client.bookingprocess;
    requires mongoose.client.icons;
    requires mongoose.client.sectionpanel;
    requires mongoose.frontend.activities.terms.routing;
    requires webfx.framework.client.i18n;
    requires webfx.framework.client.layouts;
    requires webfx.framework.client.uifilter;
    requires webfx.framework.client.uirouter;
    requires webfx.framework.shared.domain;
    requires webfx.fxkit.extracontrols;
    requires webfx.fxkit.mapper.extracontrols;

    // Implicit
    requires webfx.platform.shared.util;
    requires webfx.framework.client.activity;

    // Exported packages
    exports mongoose.frontend.activities.terms;

    // Provided services
    provides webfx.framework.client.ui.uirouter.UiRoute with mongoose.frontend.activities.terms.TermsUiRoute;

}