// Generated by WebFx

module webfx.platform.vertx.update.impl.postgres.mysql.jdbc {

    // Direct dependencies modules
    requires webfx.platform.shared.datasource;
    requires webfx.platform.shared.update;
    requires webfx.platform.vertx.queryupdate;

    // Exported packages
    exports webfx.platform.vertx.services.update.spi.impl;

    // Provided services
    provides webfx.platform.shared.services.update.spi.UpdateServiceProvider with webfx.platform.vertx.services.update.spi.impl.VertxUpdateServiceProvider;

}