// Generated by WebFx

module webfx.demo.tallycounter.application {

    // Direct dependencies modules
    requires javafx.base;
    requires javafx.graphics;
    requires webfx.lib.odometer;

    // Exported packages
    exports webfx.demo.tallycounter;

    // Provided services
    provides javafx.application.Application with webfx.demo.tallycounter.TallyCounterApplication;

}