// Generated by WebFx

module mongoose.backend.masterslave {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires mongoose.client.presentationmodel;
    requires webfx.framework.client.uifilter;
    requires webfx.framework.shared.domain;
    requires webfx.framework.shared.entity;
    requires webfx.framework.shared.expression;
    requires webfx.fxkit.extracontrols;
    requires webfx.fxkit.extratype;
    requires webfx.fxkit.util;
    requires webfx.platform.shared.util;

    // Exported packages
    exports mongoose.backend.controls.masterslave;
    exports mongoose.backend.controls.masterslave.group;

}