// Generated by WebFx

module webfx.platform.shared.shutdown.gwt {

    // Direct dependencies modules
    requires elemental2.dom;
    requires webfx.platform.shared.shutdown;

    // Exported packages
    exports webfx.platform.shared.services.shutdown.spi.impl.gwt;

}