// Generated by WebFx

module webfx.platform.client.storage.gwt {

    // Direct dependencies modules
    requires gwt.user;
    requires java.base;
    requires webfx.platform.client.storage;

    // Exported packages
    exports webfx.platform.client.services.storage.spi.impl.gwt;

}