// Generated by WebFx

module webfx.fxkit.extratype {

    // Direct dependencies modules
    requires java.base;

    // Exported packages
    exports webfx.fxkit.extra.label;
    exports webfx.fxkit.extra.type;

}