// Generated by WebFx

module webfx.framework.client.orm.filter.visual {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires webfx.extras.cell;
    requires webfx.extras.label;
    requires webfx.extras.type;
    requires webfx.extras.visual;
    requires webfx.framework.client.i18n;
    requires webfx.framework.client.orm.dql;
    requires webfx.framework.client.orm.filter;
    requires webfx.framework.shared.orm.domain;
    requires webfx.framework.shared.orm.entity;
    requires webfx.framework.shared.orm.expression;
    requires webfx.framework.shared.util;
    requires webfx.kit.util;
    requires webfx.platform.shared.json;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.framework.client.orm.entity.filter.visual;
    exports webfx.framework.client.orm.mapping.entity_to_visual;

}