// Generated by WebFx

module webfx.platform.vertx.scheduler.impl {

    // Direct dependencies modules
    requires vertx.core;
    requires webfx.platform.shared.scheduler;
    requires webfx.platform.vertx.instance;

    // Exported packages
    exports webfx.platform.vertx.services.scheduler.spi.impl;

    // Provided services
    provides webfx.platform.shared.services.scheduler.spi.SchedulerProvider with webfx.platform.vertx.services.scheduler.spi.impl.VertxSchedulerProvider;

}