// Generated by WebFx

module mongoose.backend.operations.mail {

    // Direct dependencies modules
    requires javafx.graphics;
    requires mongoose.shared.entities;
    requires webfx.framework.shared.operation;
    requires webfx.platform.shared.util;

    // Exported packages
    exports mongoose.backend.operations.entities.mail;

}