// This java module file was generated by WebFx

module mongoose.frontend.activities.contactus {

    // Direct dependencies modules
    requires javafx.controls;
    requires javafx.graphics;
    requires mongoose.client.activity;
    requires mongoose.client.validation;
    requires mongoose.frontend.activities.cart.routing;
    requires mongoose.frontend.activities.contactus.routing;
    requires mongoose.shared.entities;
    requires webfx.framework.client.action;
    requires webfx.framework.client.layouts;
    requires webfx.framework.client.uirouter;
    requires webfx.framework.client.util;
    requires webfx.framework.shared.domain;
    requires webfx.framework.shared.entity;
    requires webfx.platform.client.uischeduler;
    requires webfx.platform.client.windowlocation;
    requires webfx.platform.shared.log;
    requires webfx.platform.shared.util;

    // Implicit
    requires webfx.platform.shared.update;
    requires webfx.framework.client.activity;

    // Exported packages
    exports mongoose.frontend.activities.contactus;

    // Provided services
    provides webfx.framework.client.ui.uirouter.UiRoute with mongoose.frontend.activities.contactus.ContactUsUiRoute;

}