// Generated by WebFx

module webfx.platform.shared.submit {

    // Direct dependencies modules
    requires java.base;
    requires webfx.platform.shared.buscall;
    requires webfx.platform.shared.datascope;
    requires webfx.platform.shared.datasource;
    requires webfx.platform.shared.json;
    requires webfx.platform.shared.serial;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.platform.shared.services.submit;
    exports webfx.platform.shared.services.submit.spi;
    exports webfx.platform.shared.services.submit.spi.impl;

    // Used services
    uses webfx.platform.shared.services.submit.spi.SubmitServiceProvider;

    // Provided services
    provides webfx.platform.shared.services.buscall.spi.BusCallEndpoint with webfx.platform.shared.services.submit.ExecuteSubmitBusCallEndpoint, webfx.platform.shared.services.submit.ExecuteSubmitBatchBusCallEndpoint;
    provides webfx.platform.shared.services.serial.spi.SerialCodec with webfx.platform.shared.services.submit.SubmitArgument.ProvidedSerialCodec, webfx.platform.shared.services.submit.SubmitResult.ProvidedSerialCodec, webfx.platform.shared.services.submit.GeneratedKeyBatchIndex.ProvidedSerialCodec;

}