// This file was automatically generated by WebFx

module webfx.platform.client.windowhistory.web {

    // Direct dependencies modules
    requires webfx.platform.shared.util;
    requires webfx.platform.shared.json;
    requires java.base;
    requires webfx.platform.shared.log;
    requires webfx.platform.client.uischeduler;
    requires webfx.platform.client.windowhistory;
    requires webfx.platform.client.windowlocation;

    // Exported packages
    exports webfx.platform.client.services.windowhistory.spi.impl.web;

    // Used services
    uses webfx.platform.client.services.windowhistory.spi.impl.web.JsWindowHistory;

}