// This java module file was generated by WebFx

module mongoose.frontend.activities.payment {

    // Direct dependencies modules
    requires java.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires mongoose.client.sectionpanel;
    requires mongoose.frontend.activities.cart;
    requires mongoose.frontend.activities.payment.routing;
    requires mongoose.shared.domain;
    requires mongoose.shared.entities;
    requires webfx.framework.client.action;
    requires webfx.framework.client.controls;
    requires webfx.framework.client.i18n;
    requires webfx.framework.client.layouts;
    requires webfx.framework.client.uirouter;
    requires webfx.framework.shared.domain;
    requires webfx.framework.shared.entity;
    requires webfx.fxkit.extracontrols;
    requires webfx.platform.client.uischeduler;
    requires webfx.platform.client.websocketbus;
    requires webfx.platform.client.windowlocation;
    requires webfx.platform.shared.bus;
    requires webfx.platform.shared.log;
    requires webfx.platform.shared.util;

    // Implicit
    requires webfx.framework.client.activity;
    requires mongoose.client.aggregates;
    requires webfx.platform.shared.update;

    // Exported packages
    exports mongoose.frontend.activities.payment;

    // Provided services
    provides webfx.framework.client.ui.uirouter.UiRoute with mongoose.frontend.activities.payment.PaymentUiRoute;

}