// Generated by WebFx

module webfx.platform.client.storage {

    // Direct dependencies modules
    requires java.base;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.platform.client.services.storage;
    exports webfx.platform.client.services.storage.spi;

    // Used services
    uses webfx.platform.client.services.storage.spi.LocalStorageProvider;
    uses webfx.platform.client.services.storage.spi.SessionStorageProvider;

}