// Generated by WebFx

module webfx.framework.client.validation {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;

    // Exported packages
    exports webfx.framework.client.ui.validation.controlsfx.control.decoration;
    exports webfx.framework.client.ui.validation.controlsfx.impl;
    exports webfx.framework.client.ui.validation.controlsfx.impl.skin;
    exports webfx.framework.client.ui.validation.controlsfx.tools;
    exports webfx.framework.client.ui.validation.controlsfx.validation;
    exports webfx.framework.client.ui.validation.controlsfx.validation.decoration;
    exports webfx.framework.client.ui.validation.mvvmfx;
    exports webfx.framework.client.ui.validation.mvvmfx.visualization;

    // Resources packages
    opens webfx.framework.client.ui.validation.controlsfx.images;

}