// Generated by WebFx

module webfx.tutorial.service.theme.light {

    // Direct dependencies modules
    requires webfx.tutorial.service.theme;

    // Exported packages
    exports webfx.tutorial.service.services.theme.spi.impl.light;

}