// Generated by WebFx

module mongoose.client.activity {

    // Direct dependencies modules
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires mongoose.client.aggregates;
    requires mongoose.client.businesslogic;
    requires webfx.framework.client.controls;
    requires webfx.framework.client.domain;
    requires webfx.framework.client.layouts;
    requires webfx.framework.client.uirouter;
    requires webfx.framework.client.util;
    requires webfx.framework.shared.domain;
    requires webfx.framework.shared.expression;
    requires webfx.fxkit.extracontrols;
    requires webfx.fxkit.util;
    requires webfx.platform.shared.json;
    requires webfx.platform.shared.log;
    requires webfx.platform.shared.query;
    requires webfx.platform.shared.util;

    // Exported packages
    exports mongoose.client.activity;
    exports mongoose.client.activity.eventdependent;
    exports mongoose.client.activity.organizationdependent;
    exports mongoose.client.activity.table;
    exports mongoose.client.activity.themes;

}