// Generated by WebFx

module webfx.framework.server.querypush.simple {

    // Direct dependencies modules
    requires java.base;
    requires webfx.framework.server.querypush;
    requires webfx.framework.shared.querypush;
    requires webfx.platform.shared.datascope;
    requires webfx.platform.shared.query;
    requires webfx.platform.shared.util;

    // Exported packages
    exports webfx.framework.server.services.querypush.spi.impl.simple;

    // Provided services
    provides webfx.framework.shared.services.querypush.spi.QueryPushServiceProvider with webfx.framework.server.services.querypush.spi.impl.simple.SimpleInMemoryServerQueryPushServiceProvider;

}