// Generated by WebFx

module webfx.lib.mvvmfx.validation {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires webfx.lib.controlsfx.validation;

    // Exported packages
    exports de.saxsys.mvvmfx.utils.validation;
    exports de.saxsys.mvvmfx.utils.validation.visualization;

}